<?xml version="1.0" encoding="utf-8"?><Database Name="SinhVien" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.SinhVien" Member="SinhViens">
    <Type Name="SinhVien">
      <Column Name="MSSV" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Khoa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lop" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiemTB" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
</Database>